console.clear();

const Acl = require('./src/v1/helpers/acl');

const acl = new Acl();

acl.addRole('admin');
acl.addRole('manager');
acl.addRole('manager-sales', 'manager');
acl.addRole('manager-collections', 'manager');
acl.addRole('supervisor');
acl.addRole('supervisor-sales', 'supervisor');
acl.addRole('supervisor-collections', 'supervisor');
acl.addRole('operator');
acl.addRole('operator-sales', 'operator');
acl.addRole('operator-collections', 'operator');
acl.addRole('guest');

acl.allow('guest', ['sales', 'collections'], ['list', 'show']);
acl.allow('operator-collections', 'collections', ['list', 'show', 'create']);
acl.allow('operator-sales', 'sales', ['list', 'show', 'create']);
acl.allow('supervisor-collections', 'collections', ['list', 'show', 'create', 'update']);
acl.allow('supervisor-sales', 'sales', ['list', 'show', 'create', 'update']);
acl.allow('supervisor', 'registration', ['list', 'show', 'create', 'update']);
acl.allow('manager-collections', 'collections');
acl.allow('manager-sales', 'sales');
acl.allow('manager', 'acl', ['list', 'show']);
acl.allow('manager', 'registration');
acl.allow('admin');

function assertFalse(a) {
    return a === false;
}

function assertTrue(a) {
    return a === true;
}

const tests = [];

tests.push(assertFalse(acl.isAllowed('guest', 'acl', null)));
tests.push(assertFalse(acl.isAllowed('guest', 'acl', 'list')));
tests.push(assertFalse(acl.isAllowed('guest', 'acl', 'create')));
tests.push(assertFalse(acl.isAllowed('guest', 'acl', 'show')));
tests.push(assertFalse(acl.isAllowed('guest', 'acl', 'update')));
tests.push(assertFalse(acl.isAllowed('guest', 'acl', 'delete')));
tests.push(assertFalse(acl.isAllowed('guest', 'registration', null)));
tests.push(assertFalse(acl.isAllowed('guest', 'registration', 'list')));
tests.push(assertFalse(acl.isAllowed('guest', 'registration', 'create')));
tests.push(assertFalse(acl.isAllowed('guest', 'registration', 'show')));
tests.push(assertFalse(acl.isAllowed('guest', 'registration', 'update')));
tests.push(assertFalse(acl.isAllowed('guest', 'registration', 'delete')));
tests.push(assertFalse(acl.isAllowed('guest', 'sales', null)));
tests.push(assertTrue(acl.isAllowed('guest', 'sales', 'list')));
tests.push(assertFalse(acl.isAllowed('guest', 'sales', 'create')));
tests.push(assertTrue(acl.isAllowed('guest', 'sales', 'show')));
tests.push(assertFalse(acl.isAllowed('guest', 'sales', 'update')));
tests.push(assertFalse(acl.isAllowed('guest', 'sales', 'delete')));
tests.push(assertFalse(acl.isAllowed('guest', 'collections', null)));
tests.push(assertTrue(acl.isAllowed('guest', 'collections', 'list')));
tests.push(assertFalse(acl.isAllowed('guest', 'collections', 'create')));
tests.push(assertTrue(acl.isAllowed('guest', 'collections', 'show')));
tests.push(assertFalse(acl.isAllowed('guest', 'collections', 'update')));
tests.push(assertFalse(acl.isAllowed('guest', 'collections', 'delete')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'acl', null)));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'acl', 'list')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'acl', 'create')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'acl', 'show')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'acl', 'update')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'acl', 'delete')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'registration', null)));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'registration', 'list')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'registration', 'create')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'registration', 'show')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'registration', 'update')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'registration', 'delete')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'sales', null)));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'sales', 'list')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'sales', 'create')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'sales', 'show')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'sales', 'update')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'sales', 'delete')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'collections', null)));
tests.push(assertTrue(acl.isAllowed('operator-collections', 'collections', 'list')));
tests.push(assertTrue(acl.isAllowed('operator-collections', 'collections', 'create')));
tests.push(assertTrue(acl.isAllowed('operator-collections', 'collections', 'show')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'collections', 'update')));
tests.push(assertFalse(acl.isAllowed('operator-collections', 'collections', 'delete')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'acl', null)));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'acl', 'list')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'acl', 'create')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'acl', 'show')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'acl', 'update')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'acl', 'delete')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'registration', null)));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'registration', 'list')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'registration', 'create')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'registration', 'show')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'registration', 'update')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'registration', 'delete')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'sales', null)));
tests.push(assertTrue(acl.isAllowed('operator-sales', 'sales', 'list')));
tests.push(assertTrue(acl.isAllowed('operator-sales', 'sales', 'create')));
tests.push(assertTrue(acl.isAllowed('operator-sales', 'sales', 'show')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'sales', 'update')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'sales', 'delete')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'collections', null)));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'collections', 'list')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'collections', 'create')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'collections', 'show')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'collections', 'update')));
tests.push(assertFalse(acl.isAllowed('operator-sales', 'collections', 'delete')));
tests.push(assertFalse(acl.isAllowed('operator', 'acl', null)));
tests.push(assertFalse(acl.isAllowed('operator', 'acl', 'list')));
tests.push(assertFalse(acl.isAllowed('operator', 'acl', 'create')));
tests.push(assertFalse(acl.isAllowed('operator', 'acl', 'show')));
tests.push(assertFalse(acl.isAllowed('operator', 'acl', 'update')));
tests.push(assertFalse(acl.isAllowed('operator', 'acl', 'delete')));
tests.push(assertFalse(acl.isAllowed('operator', 'registration', null)));
tests.push(assertFalse(acl.isAllowed('operator', 'registration', 'list')));
tests.push(assertFalse(acl.isAllowed('operator', 'registration', 'create')));
tests.push(assertFalse(acl.isAllowed('operator', 'registration', 'show')));
tests.push(assertFalse(acl.isAllowed('operator', 'registration', 'update')));
tests.push(assertFalse(acl.isAllowed('operator', 'registration', 'delete')));
tests.push(assertFalse(acl.isAllowed('operator', 'sales', null)));
tests.push(assertFalse(acl.isAllowed('operator', 'sales', 'list')));
tests.push(assertFalse(acl.isAllowed('operator', 'sales', 'create')));
tests.push(assertFalse(acl.isAllowed('operator', 'sales', 'show')));
tests.push(assertFalse(acl.isAllowed('operator', 'sales', 'update')));
tests.push(assertFalse(acl.isAllowed('operator', 'sales', 'delete')));
tests.push(assertFalse(acl.isAllowed('operator', 'collections', null)));
tests.push(assertFalse(acl.isAllowed('operator', 'collections', 'list')));
tests.push(assertFalse(acl.isAllowed('operator', 'collections', 'create')));
tests.push(assertFalse(acl.isAllowed('operator', 'collections', 'show')));
tests.push(assertFalse(acl.isAllowed('operator', 'collections', 'update')));
tests.push(assertFalse(acl.isAllowed('operator', 'collections', 'delete')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'acl', null)));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'acl', 'list')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'acl', 'create')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'acl', 'show')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'acl', 'update')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'acl', 'delete')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'registration', null)));
tests.push(assertTrue(acl.isAllowed('supervisor-collections', 'registration', 'list')));
tests.push(assertTrue(acl.isAllowed('supervisor-collections', 'registration', 'create')));
tests.push(assertTrue(acl.isAllowed('supervisor-collections', 'registration', 'show')));
tests.push(assertTrue(acl.isAllowed('supervisor-collections', 'registration', 'update')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'registration', 'delete')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'sales', null)));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'sales', 'list')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'sales', 'create')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'sales', 'show')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'sales', 'update')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'sales', 'delete')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'collections', null)));
tests.push(assertTrue(acl.isAllowed('supervisor-collections', 'collections', 'list')));
tests.push(assertTrue(acl.isAllowed('supervisor-collections', 'collections', 'create')));
tests.push(assertTrue(acl.isAllowed('supervisor-collections', 'collections', 'show')));
tests.push(assertTrue(acl.isAllowed('supervisor-collections', 'collections', 'update')));
tests.push(assertFalse(acl.isAllowed('supervisor-collections', 'collections', 'delete')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'acl', null)));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'acl', 'list')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'acl', 'create')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'acl', 'show')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'acl', 'update')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'acl', 'delete')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'registration', null)));
tests.push(assertTrue(acl.isAllowed('supervisor-sales', 'registration', 'list')));
tests.push(assertTrue(acl.isAllowed('supervisor-sales', 'registration', 'create')));
tests.push(assertTrue(acl.isAllowed('supervisor-sales', 'registration', 'show')));
tests.push(assertTrue(acl.isAllowed('supervisor-sales', 'registration', 'update')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'registration', 'delete')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'sales', null)));
tests.push(assertTrue(acl.isAllowed('supervisor-sales', 'sales', 'list')));
tests.push(assertTrue(acl.isAllowed('supervisor-sales', 'sales', 'create')));
tests.push(assertTrue(acl.isAllowed('supervisor-sales', 'sales', 'show')));
tests.push(assertTrue(acl.isAllowed('supervisor-sales', 'sales', 'update')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'sales', 'delete')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'collections', null)));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'collections', 'list')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'collections', 'create')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'collections', 'show')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'collections', 'update')));
tests.push(assertFalse(acl.isAllowed('supervisor-sales', 'collections', 'delete')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'acl', null)));
tests.push(assertFalse(acl.isAllowed('supervisor', 'acl', 'list')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'acl', 'create')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'acl', 'show')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'acl', 'update')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'acl', 'delete')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'registration', null)));
tests.push(assertTrue(acl.isAllowed('supervisor', 'registration', 'list')));
tests.push(assertTrue(acl.isAllowed('supervisor', 'registration', 'create')));
tests.push(assertTrue(acl.isAllowed('supervisor', 'registration', 'show')));
tests.push(assertTrue(acl.isAllowed('supervisor', 'registration', 'update')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'registration', 'delete')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'sales', null)));
tests.push(assertFalse(acl.isAllowed('supervisor', 'sales', 'list')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'sales', 'create')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'sales', 'show')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'sales', 'update')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'sales', 'delete')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'collections', null)));
tests.push(assertFalse(acl.isAllowed('supervisor', 'collections', 'list')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'collections', 'create')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'collections', 'show')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'collections', 'update')));
tests.push(assertFalse(acl.isAllowed('supervisor', 'collections', 'delete')));
tests.push(assertFalse(acl.isAllowed('manager-collections', 'acl', null)));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'acl', 'list')));
tests.push(assertFalse(acl.isAllowed('manager-collections', 'acl', 'create')));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'acl', 'show')));
tests.push(assertFalse(acl.isAllowed('manager-collections', 'acl', 'update')));
tests.push(assertFalse(acl.isAllowed('manager-collections', 'acl', 'delete')));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'registration', null)));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'registration', 'list')));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'registration', 'create')));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'registration', 'show')));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'registration', 'update')));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'registration', 'delete')));
tests.push(assertFalse(acl.isAllowed('manager-collections', 'sales', null)));
tests.push(assertFalse(acl.isAllowed('manager-collections', 'sales', 'list')));
tests.push(assertFalse(acl.isAllowed('manager-collections', 'sales', 'create')));
tests.push(assertFalse(acl.isAllowed('manager-collections', 'sales', 'show')));
tests.push(assertFalse(acl.isAllowed('manager-collections', 'sales', 'update')));
tests.push(assertFalse(acl.isAllowed('manager-collections', 'sales', 'delete')));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'collections', null)));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'collections', 'list')));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'collections', 'create')));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'collections', 'show')));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'collections', 'update')));
tests.push(assertTrue(acl.isAllowed('manager-collections', 'collections', 'delete')));
tests.push(assertFalse(acl.isAllowed('manager-sales', 'acl', null)));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'acl', 'list')));
tests.push(assertFalse(acl.isAllowed('manager-sales', 'acl', 'create')));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'acl', 'show')));
tests.push(assertFalse(acl.isAllowed('manager-sales', 'acl', 'update')));
tests.push(assertFalse(acl.isAllowed('manager-sales', 'acl', 'delete')));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'registration', null)));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'registration', 'list')));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'registration', 'create')));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'registration', 'show')));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'registration', 'update')));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'registration', 'delete')));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'sales', null)));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'sales', 'list')));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'sales', 'create')));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'sales', 'show')));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'sales', 'update')));
tests.push(assertTrue(acl.isAllowed('manager-sales', 'sales', 'delete')));
tests.push(assertFalse(acl.isAllowed('manager-sales', 'collections', null)));
tests.push(assertFalse(acl.isAllowed('manager-sales', 'collections', 'list')));
tests.push(assertFalse(acl.isAllowed('manager-sales', 'collections', 'create')));
tests.push(assertFalse(acl.isAllowed('manager-sales', 'collections', 'show')));
tests.push(assertFalse(acl.isAllowed('manager-sales', 'collections', 'update')));
tests.push(assertFalse(acl.isAllowed('manager-sales', 'collections', 'delete')));
tests.push(assertFalse(acl.isAllowed('manager', 'acl', null)));
tests.push(assertTrue(acl.isAllowed('manager', 'acl', 'list')));
tests.push(assertFalse(acl.isAllowed('manager', 'acl', 'create')));
tests.push(assertTrue(acl.isAllowed('manager', 'acl', 'show')));
tests.push(assertFalse(acl.isAllowed('manager', 'acl', 'update')));
tests.push(assertFalse(acl.isAllowed('manager', 'acl', 'delete')));
tests.push(assertTrue(acl.isAllowed('manager', 'registration', null)));
tests.push(assertTrue(acl.isAllowed('manager', 'registration', 'list')));
tests.push(assertTrue(acl.isAllowed('manager', 'registration', 'create')));
tests.push(assertTrue(acl.isAllowed('manager', 'registration', 'show')));
tests.push(assertTrue(acl.isAllowed('manager', 'registration', 'update')));
tests.push(assertTrue(acl.isAllowed('manager', 'registration', 'delete')));
tests.push(assertFalse(acl.isAllowed('manager', 'sales', null)));
tests.push(assertFalse(acl.isAllowed('manager', 'sales', 'list')));
tests.push(assertFalse(acl.isAllowed('manager', 'sales', 'create')));
tests.push(assertFalse(acl.isAllowed('manager', 'sales', 'show')));
tests.push(assertFalse(acl.isAllowed('manager', 'sales', 'update')));
tests.push(assertFalse(acl.isAllowed('manager', 'sales', 'delete')));
tests.push(assertFalse(acl.isAllowed('manager', 'collections', null)));
tests.push(assertFalse(acl.isAllowed('manager', 'collections', 'list')));
tests.push(assertFalse(acl.isAllowed('manager', 'collections', 'create')));
tests.push(assertFalse(acl.isAllowed('manager', 'collections', 'show')));
tests.push(assertFalse(acl.isAllowed('manager', 'collections', 'update')));
tests.push(assertFalse(acl.isAllowed('manager', 'collections', 'delete')));
tests.push(assertTrue(acl.isAllowed('admin', 'acl', null)));
tests.push(assertTrue(acl.isAllowed('admin', 'acl', 'list')));
tests.push(assertTrue(acl.isAllowed('admin', 'acl', 'create')));
tests.push(assertTrue(acl.isAllowed('admin', 'acl', 'show')));
tests.push(assertTrue(acl.isAllowed('admin', 'acl', 'update')));
tests.push(assertTrue(acl.isAllowed('admin', 'acl', 'delete')));
tests.push(assertTrue(acl.isAllowed('admin', 'registration', null)));
tests.push(assertTrue(acl.isAllowed('admin', 'registration', 'list')));
tests.push(assertTrue(acl.isAllowed('admin', 'registration', 'create')));
tests.push(assertTrue(acl.isAllowed('admin', 'registration', 'show')));
tests.push(assertTrue(acl.isAllowed('admin', 'registration', 'update')));
tests.push(assertTrue(acl.isAllowed('admin', 'registration', 'delete')));
tests.push(assertTrue(acl.isAllowed('admin', 'sales', null)));
tests.push(assertTrue(acl.isAllowed('admin', 'sales', 'list')));
tests.push(assertTrue(acl.isAllowed('admin', 'sales', 'create')));
tests.push(assertTrue(acl.isAllowed('admin', 'sales', 'show')));
tests.push(assertTrue(acl.isAllowed('admin', 'sales', 'update')));
tests.push(assertTrue(acl.isAllowed('admin', 'sales', 'delete')));
tests.push(assertTrue(acl.isAllowed('admin', 'collections', null)));
tests.push(assertTrue(acl.isAllowed('admin', 'collections', 'list')));
tests.push(assertTrue(acl.isAllowed('admin', 'collections', 'create')));
tests.push(assertTrue(acl.isAllowed('admin', 'collections', 'show')));
tests.push(assertTrue(acl.isAllowed('admin', 'collections', 'update')));
tests.push(assertTrue(acl.isAllowed('admin', 'collections', 'delete')));

console.log('success:', tests.filter(test => test).length);
console.log('errors:', tests.filter(test => !test).length);
